// Import Library
import React, { Fragment } from 'react';
import { IoDownloadOutline } from 'react-icons/io5';
import { useSelector } from 'react-redux';

// Import Custom Library
import { getAuthData } from '@/config/store/reducer/authSlice';

// Import Components
import BreadCrumb from '@/components/core/BreadCrumb';

export default function Credentials() {
    
    const authData = useSelector(getAuthData);

    return (
        <Fragment>
            <BreadCrumb
                list={[
                    { label: 'Credentials' }
                ]}
            />
            <div className='bg-night-300 border-b-8 border-night-400/70 px-6 py-8 relative w-full'>
                <p className='font-bold text-2xl'>Credentials</p>
            </div>
            <div className='p-6 relative w-full'>
                <p className='text-xl'>Transaction Payment Gateway</p>
                <p className='mt-2 text-sm'>Please use this Client ID and Client Secret to get your access token. You will need to know your Access Token (Client ID and Client Secret) and Merchant ID (MID) to communicate with YUKK. Please use the Development server while you are still in development</p>
                <div className='bg-night-300 grid grid-cols-[repeat(auto-fit,_minmax(300px,_1fr))] gap-4 items-center mt-8 p-4 relative rounded-lg'>
                    <div className='overflow-auto relative w-full'>
                        <p className='text-sm'>API Keys</p>
                        <div className='border-[1px] border-night-100 gap-4 grid mt-4 p-4 rounded relative text-sm w-full'>
                            <div className='grid items-start gap-2 md:gap-4 md:grid-cols-4'>
                                <p className='font-bold'>Client ID</p>
                                <p className='break-all col-span-3'>{authData?.client?.client_code}</p>
                            </div>
                            <div className='grid items-start gap-2 md:gap-4 md:grid-cols-4'>
                                <p className='font-bold'>Client Secret (Development)</p>
                                <p className='break-all col-span-3'>{authData?.client?.client_secret_development}</p>
                            </div>
                            <div className='grid items-start gap-2 md:gap-4 md:grid-cols-4'>
                                <p className='font-bold'>Client Secret (Production)</p>
                                <p className='break-all col-span-3'>{authData?.client?.client_secret_production}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className='bg-info mt-4 px-3 py-2'>
                    <p className='text-xs'>This keys is auto generated by system and should not be changed.</p>
                </div>
                <div className='px-3 py-2 relative'>
                    <p className='mt-2 text-xs'>*) If the fields is empty please contact our support.</p>
                    <p className='font-bold mt-4 text-sm'>Tech Docs</p>
                    <button type='button' className='bg-info/80 duration-300 flex gap-1 items-center mt-4 px-6 py-2 rounded text-sm transition-colors hover:bg-info'>
                        <IoDownloadOutline size={16} />
                        Download
                    </button>
                </div>
            </div>
        </Fragment>
    )
}

Credentials.guard = true;
Credentials.layout = 'Sidebar';
Credentials.title = 'PGO Dashboard - Credentials';